
#include "Gradient.h"

#include "pbatautogen/Gradient_1_Mesh_line_Order_1_Dims_1.h"
#include "pbatautogen/Gradient_1_Mesh_line_Order_1_Dims_2.h"
#include "pbatautogen/Gradient_1_Mesh_line_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_1_Mesh_line_Order_2_Dims_1.h"
#include "pbatautogen/Gradient_1_Mesh_line_Order_2_Dims_2.h"
#include "pbatautogen/Gradient_1_Mesh_line_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_1_Mesh_line_Order_3_Dims_1.h"
#include "pbatautogen/Gradient_1_Mesh_line_Order_3_Dims_2.h"
#include "pbatautogen/Gradient_1_Mesh_line_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_1_Mesh_triangle_Order_1_Dims_2.h"
#include "pbatautogen/Gradient_1_Mesh_triangle_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_1_Mesh_triangle_Order_2_Dims_2.h"
#include "pbatautogen/Gradient_1_Mesh_triangle_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_1_Mesh_triangle_Order_3_Dims_2.h"
#include "pbatautogen/Gradient_1_Mesh_triangle_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_1_Mesh_quadrilateral_Order_1_Dims_2.h"
#include "pbatautogen/Gradient_1_Mesh_quadrilateral_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_1_Mesh_quadrilateral_Order_2_Dims_2.h"
#include "pbatautogen/Gradient_1_Mesh_quadrilateral_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_1_Mesh_quadrilateral_Order_3_Dims_2.h"
#include "pbatautogen/Gradient_1_Mesh_quadrilateral_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_1_Mesh_tetrahedron_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_1_Mesh_tetrahedron_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_1_Mesh_tetrahedron_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_1_Mesh_hexahedron_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_1_Mesh_hexahedron_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_1_Mesh_hexahedron_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_2_Mesh_line_Order_1_Dims_1.h"
#include "pbatautogen/Gradient_2_Mesh_line_Order_1_Dims_2.h"
#include "pbatautogen/Gradient_2_Mesh_line_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_2_Mesh_line_Order_2_Dims_1.h"
#include "pbatautogen/Gradient_2_Mesh_line_Order_2_Dims_2.h"
#include "pbatautogen/Gradient_2_Mesh_line_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_2_Mesh_line_Order_3_Dims_1.h"
#include "pbatautogen/Gradient_2_Mesh_line_Order_3_Dims_2.h"
#include "pbatautogen/Gradient_2_Mesh_line_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_2_Mesh_triangle_Order_1_Dims_2.h"
#include "pbatautogen/Gradient_2_Mesh_triangle_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_2_Mesh_triangle_Order_2_Dims_2.h"
#include "pbatautogen/Gradient_2_Mesh_triangle_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_2_Mesh_triangle_Order_3_Dims_2.h"
#include "pbatautogen/Gradient_2_Mesh_triangle_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_2_Mesh_quadrilateral_Order_1_Dims_2.h"
#include "pbatautogen/Gradient_2_Mesh_quadrilateral_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_2_Mesh_quadrilateral_Order_2_Dims_2.h"
#include "pbatautogen/Gradient_2_Mesh_quadrilateral_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_2_Mesh_quadrilateral_Order_3_Dims_2.h"
#include "pbatautogen/Gradient_2_Mesh_quadrilateral_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_2_Mesh_tetrahedron_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_2_Mesh_tetrahedron_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_2_Mesh_tetrahedron_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_2_Mesh_hexahedron_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_2_Mesh_hexahedron_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_2_Mesh_hexahedron_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_3_Mesh_line_Order_1_Dims_1.h"
#include "pbatautogen/Gradient_3_Mesh_line_Order_1_Dims_2.h"
#include "pbatautogen/Gradient_3_Mesh_line_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_3_Mesh_line_Order_2_Dims_1.h"
#include "pbatautogen/Gradient_3_Mesh_line_Order_2_Dims_2.h"
#include "pbatautogen/Gradient_3_Mesh_line_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_3_Mesh_line_Order_3_Dims_1.h"
#include "pbatautogen/Gradient_3_Mesh_line_Order_3_Dims_2.h"
#include "pbatautogen/Gradient_3_Mesh_line_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_3_Mesh_triangle_Order_1_Dims_2.h"
#include "pbatautogen/Gradient_3_Mesh_triangle_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_3_Mesh_triangle_Order_2_Dims_2.h"
#include "pbatautogen/Gradient_3_Mesh_triangle_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_3_Mesh_triangle_Order_3_Dims_2.h"
#include "pbatautogen/Gradient_3_Mesh_triangle_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_3_Mesh_quadrilateral_Order_1_Dims_2.h"
#include "pbatautogen/Gradient_3_Mesh_quadrilateral_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_3_Mesh_quadrilateral_Order_2_Dims_2.h"
#include "pbatautogen/Gradient_3_Mesh_quadrilateral_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_3_Mesh_quadrilateral_Order_3_Dims_2.h"
#include "pbatautogen/Gradient_3_Mesh_quadrilateral_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_3_Mesh_tetrahedron_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_3_Mesh_tetrahedron_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_3_Mesh_tetrahedron_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_3_Mesh_hexahedron_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_3_Mesh_hexahedron_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_3_Mesh_hexahedron_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_4_Mesh_line_Order_1_Dims_1.h"
#include "pbatautogen/Gradient_4_Mesh_line_Order_1_Dims_2.h"
#include "pbatautogen/Gradient_4_Mesh_line_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_4_Mesh_line_Order_2_Dims_1.h"
#include "pbatautogen/Gradient_4_Mesh_line_Order_2_Dims_2.h"
#include "pbatautogen/Gradient_4_Mesh_line_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_4_Mesh_line_Order_3_Dims_1.h"
#include "pbatautogen/Gradient_4_Mesh_line_Order_3_Dims_2.h"
#include "pbatautogen/Gradient_4_Mesh_line_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_4_Mesh_triangle_Order_1_Dims_2.h"
#include "pbatautogen/Gradient_4_Mesh_triangle_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_4_Mesh_triangle_Order_2_Dims_2.h"
#include "pbatautogen/Gradient_4_Mesh_triangle_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_4_Mesh_triangle_Order_3_Dims_2.h"
#include "pbatautogen/Gradient_4_Mesh_triangle_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_4_Mesh_quadrilateral_Order_1_Dims_2.h"
#include "pbatautogen/Gradient_4_Mesh_quadrilateral_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_4_Mesh_quadrilateral_Order_2_Dims_2.h"
#include "pbatautogen/Gradient_4_Mesh_quadrilateral_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_4_Mesh_quadrilateral_Order_3_Dims_2.h"
#include "pbatautogen/Gradient_4_Mesh_quadrilateral_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_4_Mesh_tetrahedron_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_4_Mesh_tetrahedron_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_4_Mesh_tetrahedron_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_4_Mesh_hexahedron_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_4_Mesh_hexahedron_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_4_Mesh_hexahedron_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_5_Mesh_line_Order_1_Dims_1.h"
#include "pbatautogen/Gradient_5_Mesh_line_Order_1_Dims_2.h"
#include "pbatautogen/Gradient_5_Mesh_line_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_5_Mesh_line_Order_2_Dims_1.h"
#include "pbatautogen/Gradient_5_Mesh_line_Order_2_Dims_2.h"
#include "pbatautogen/Gradient_5_Mesh_line_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_5_Mesh_line_Order_3_Dims_1.h"
#include "pbatautogen/Gradient_5_Mesh_line_Order_3_Dims_2.h"
#include "pbatautogen/Gradient_5_Mesh_line_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_5_Mesh_triangle_Order_1_Dims_2.h"
#include "pbatautogen/Gradient_5_Mesh_triangle_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_5_Mesh_triangle_Order_2_Dims_2.h"
#include "pbatautogen/Gradient_5_Mesh_triangle_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_5_Mesh_triangle_Order_3_Dims_2.h"
#include "pbatautogen/Gradient_5_Mesh_triangle_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_5_Mesh_quadrilateral_Order_1_Dims_2.h"
#include "pbatautogen/Gradient_5_Mesh_quadrilateral_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_5_Mesh_quadrilateral_Order_2_Dims_2.h"
#include "pbatautogen/Gradient_5_Mesh_quadrilateral_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_5_Mesh_quadrilateral_Order_3_Dims_2.h"
#include "pbatautogen/Gradient_5_Mesh_quadrilateral_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_5_Mesh_tetrahedron_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_5_Mesh_tetrahedron_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_5_Mesh_tetrahedron_Order_3_Dims_3.h"
#include "pbatautogen/Gradient_5_Mesh_hexahedron_Order_1_Dims_3.h"
#include "pbatautogen/Gradient_5_Mesh_hexahedron_Order_2_Dims_3.h"
#include "pbatautogen/Gradient_5_Mesh_hexahedron_Order_3_Dims_3.h"

namespace pbat {
namespace py {
namespace fem {

void BindGradient(pybind11::module& m)
{
    BindGradient_1_Mesh_line_Order_1_Dims_1(m);
BindGradient_1_Mesh_line_Order_1_Dims_2(m);
BindGradient_1_Mesh_line_Order_1_Dims_3(m);
BindGradient_1_Mesh_line_Order_2_Dims_1(m);
BindGradient_1_Mesh_line_Order_2_Dims_2(m);
BindGradient_1_Mesh_line_Order_2_Dims_3(m);
BindGradient_1_Mesh_line_Order_3_Dims_1(m);
BindGradient_1_Mesh_line_Order_3_Dims_2(m);
BindGradient_1_Mesh_line_Order_3_Dims_3(m);
BindGradient_1_Mesh_triangle_Order_1_Dims_2(m);
BindGradient_1_Mesh_triangle_Order_1_Dims_3(m);
BindGradient_1_Mesh_triangle_Order_2_Dims_2(m);
BindGradient_1_Mesh_triangle_Order_2_Dims_3(m);
BindGradient_1_Mesh_triangle_Order_3_Dims_2(m);
BindGradient_1_Mesh_triangle_Order_3_Dims_3(m);
BindGradient_1_Mesh_quadrilateral_Order_1_Dims_2(m);
BindGradient_1_Mesh_quadrilateral_Order_1_Dims_3(m);
BindGradient_1_Mesh_quadrilateral_Order_2_Dims_2(m);
BindGradient_1_Mesh_quadrilateral_Order_2_Dims_3(m);
BindGradient_1_Mesh_quadrilateral_Order_3_Dims_2(m);
BindGradient_1_Mesh_quadrilateral_Order_3_Dims_3(m);
BindGradient_1_Mesh_tetrahedron_Order_1_Dims_3(m);
BindGradient_1_Mesh_tetrahedron_Order_2_Dims_3(m);
BindGradient_1_Mesh_tetrahedron_Order_3_Dims_3(m);
BindGradient_1_Mesh_hexahedron_Order_1_Dims_3(m);
BindGradient_1_Mesh_hexahedron_Order_2_Dims_3(m);
BindGradient_1_Mesh_hexahedron_Order_3_Dims_3(m);
BindGradient_2_Mesh_line_Order_1_Dims_1(m);
BindGradient_2_Mesh_line_Order_1_Dims_2(m);
BindGradient_2_Mesh_line_Order_1_Dims_3(m);
BindGradient_2_Mesh_line_Order_2_Dims_1(m);
BindGradient_2_Mesh_line_Order_2_Dims_2(m);
BindGradient_2_Mesh_line_Order_2_Dims_3(m);
BindGradient_2_Mesh_line_Order_3_Dims_1(m);
BindGradient_2_Mesh_line_Order_3_Dims_2(m);
BindGradient_2_Mesh_line_Order_3_Dims_3(m);
BindGradient_2_Mesh_triangle_Order_1_Dims_2(m);
BindGradient_2_Mesh_triangle_Order_1_Dims_3(m);
BindGradient_2_Mesh_triangle_Order_2_Dims_2(m);
BindGradient_2_Mesh_triangle_Order_2_Dims_3(m);
BindGradient_2_Mesh_triangle_Order_3_Dims_2(m);
BindGradient_2_Mesh_triangle_Order_3_Dims_3(m);
BindGradient_2_Mesh_quadrilateral_Order_1_Dims_2(m);
BindGradient_2_Mesh_quadrilateral_Order_1_Dims_3(m);
BindGradient_2_Mesh_quadrilateral_Order_2_Dims_2(m);
BindGradient_2_Mesh_quadrilateral_Order_2_Dims_3(m);
BindGradient_2_Mesh_quadrilateral_Order_3_Dims_2(m);
BindGradient_2_Mesh_quadrilateral_Order_3_Dims_3(m);
BindGradient_2_Mesh_tetrahedron_Order_1_Dims_3(m);
BindGradient_2_Mesh_tetrahedron_Order_2_Dims_3(m);
BindGradient_2_Mesh_tetrahedron_Order_3_Dims_3(m);
BindGradient_2_Mesh_hexahedron_Order_1_Dims_3(m);
BindGradient_2_Mesh_hexahedron_Order_2_Dims_3(m);
BindGradient_2_Mesh_hexahedron_Order_3_Dims_3(m);
BindGradient_3_Mesh_line_Order_1_Dims_1(m);
BindGradient_3_Mesh_line_Order_1_Dims_2(m);
BindGradient_3_Mesh_line_Order_1_Dims_3(m);
BindGradient_3_Mesh_line_Order_2_Dims_1(m);
BindGradient_3_Mesh_line_Order_2_Dims_2(m);
BindGradient_3_Mesh_line_Order_2_Dims_3(m);
BindGradient_3_Mesh_line_Order_3_Dims_1(m);
BindGradient_3_Mesh_line_Order_3_Dims_2(m);
BindGradient_3_Mesh_line_Order_3_Dims_3(m);
BindGradient_3_Mesh_triangle_Order_1_Dims_2(m);
BindGradient_3_Mesh_triangle_Order_1_Dims_3(m);
BindGradient_3_Mesh_triangle_Order_2_Dims_2(m);
BindGradient_3_Mesh_triangle_Order_2_Dims_3(m);
BindGradient_3_Mesh_triangle_Order_3_Dims_2(m);
BindGradient_3_Mesh_triangle_Order_3_Dims_3(m);
BindGradient_3_Mesh_quadrilateral_Order_1_Dims_2(m);
BindGradient_3_Mesh_quadrilateral_Order_1_Dims_3(m);
BindGradient_3_Mesh_quadrilateral_Order_2_Dims_2(m);
BindGradient_3_Mesh_quadrilateral_Order_2_Dims_3(m);
BindGradient_3_Mesh_quadrilateral_Order_3_Dims_2(m);
BindGradient_3_Mesh_quadrilateral_Order_3_Dims_3(m);
BindGradient_3_Mesh_tetrahedron_Order_1_Dims_3(m);
BindGradient_3_Mesh_tetrahedron_Order_2_Dims_3(m);
BindGradient_3_Mesh_tetrahedron_Order_3_Dims_3(m);
BindGradient_3_Mesh_hexahedron_Order_1_Dims_3(m);
BindGradient_3_Mesh_hexahedron_Order_2_Dims_3(m);
BindGradient_3_Mesh_hexahedron_Order_3_Dims_3(m);
BindGradient_4_Mesh_line_Order_1_Dims_1(m);
BindGradient_4_Mesh_line_Order_1_Dims_2(m);
BindGradient_4_Mesh_line_Order_1_Dims_3(m);
BindGradient_4_Mesh_line_Order_2_Dims_1(m);
BindGradient_4_Mesh_line_Order_2_Dims_2(m);
BindGradient_4_Mesh_line_Order_2_Dims_3(m);
BindGradient_4_Mesh_line_Order_3_Dims_1(m);
BindGradient_4_Mesh_line_Order_3_Dims_2(m);
BindGradient_4_Mesh_line_Order_3_Dims_3(m);
BindGradient_4_Mesh_triangle_Order_1_Dims_2(m);
BindGradient_4_Mesh_triangle_Order_1_Dims_3(m);
BindGradient_4_Mesh_triangle_Order_2_Dims_2(m);
BindGradient_4_Mesh_triangle_Order_2_Dims_3(m);
BindGradient_4_Mesh_triangle_Order_3_Dims_2(m);
BindGradient_4_Mesh_triangle_Order_3_Dims_3(m);
BindGradient_4_Mesh_quadrilateral_Order_1_Dims_2(m);
BindGradient_4_Mesh_quadrilateral_Order_1_Dims_3(m);
BindGradient_4_Mesh_quadrilateral_Order_2_Dims_2(m);
BindGradient_4_Mesh_quadrilateral_Order_2_Dims_3(m);
BindGradient_4_Mesh_quadrilateral_Order_3_Dims_2(m);
BindGradient_4_Mesh_quadrilateral_Order_3_Dims_3(m);
BindGradient_4_Mesh_tetrahedron_Order_1_Dims_3(m);
BindGradient_4_Mesh_tetrahedron_Order_2_Dims_3(m);
BindGradient_4_Mesh_tetrahedron_Order_3_Dims_3(m);
BindGradient_4_Mesh_hexahedron_Order_1_Dims_3(m);
BindGradient_4_Mesh_hexahedron_Order_2_Dims_3(m);
BindGradient_4_Mesh_hexahedron_Order_3_Dims_3(m);
BindGradient_5_Mesh_line_Order_1_Dims_1(m);
BindGradient_5_Mesh_line_Order_1_Dims_2(m);
BindGradient_5_Mesh_line_Order_1_Dims_3(m);
BindGradient_5_Mesh_line_Order_2_Dims_1(m);
BindGradient_5_Mesh_line_Order_2_Dims_2(m);
BindGradient_5_Mesh_line_Order_2_Dims_3(m);
BindGradient_5_Mesh_line_Order_3_Dims_1(m);
BindGradient_5_Mesh_line_Order_3_Dims_2(m);
BindGradient_5_Mesh_line_Order_3_Dims_3(m);
BindGradient_5_Mesh_triangle_Order_1_Dims_2(m);
BindGradient_5_Mesh_triangle_Order_1_Dims_3(m);
BindGradient_5_Mesh_triangle_Order_2_Dims_2(m);
BindGradient_5_Mesh_triangle_Order_2_Dims_3(m);
BindGradient_5_Mesh_triangle_Order_3_Dims_2(m);
BindGradient_5_Mesh_triangle_Order_3_Dims_3(m);
BindGradient_5_Mesh_quadrilateral_Order_1_Dims_2(m);
BindGradient_5_Mesh_quadrilateral_Order_1_Dims_3(m);
BindGradient_5_Mesh_quadrilateral_Order_2_Dims_2(m);
BindGradient_5_Mesh_quadrilateral_Order_2_Dims_3(m);
BindGradient_5_Mesh_quadrilateral_Order_3_Dims_2(m);
BindGradient_5_Mesh_quadrilateral_Order_3_Dims_3(m);
BindGradient_5_Mesh_tetrahedron_Order_1_Dims_3(m);
BindGradient_5_Mesh_tetrahedron_Order_2_Dims_3(m);
BindGradient_5_Mesh_tetrahedron_Order_3_Dims_3(m);
BindGradient_5_Mesh_hexahedron_Order_1_Dims_3(m);
BindGradient_5_Mesh_hexahedron_Order_2_Dims_3(m);
BindGradient_5_Mesh_hexahedron_Order_3_Dims_3(m);  
}

} // namespace fem
} // namespace py
} // namespace pbat
