
#include "LaplacianMatrix.h"

#include "pbatautogen/LaplacianMatrix_1_Mesh_line_Order_1_Dims_1.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_line_Order_1_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_line_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_line_Order_2_Dims_1.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_line_Order_2_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_line_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_line_Order_3_Dims_1.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_line_Order_3_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_line_Order_3_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_triangle_Order_1_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_triangle_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_triangle_Order_2_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_triangle_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_triangle_Order_3_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_triangle_Order_3_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_quadrilateral_Order_1_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_quadrilateral_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_quadrilateral_Order_2_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_quadrilateral_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_quadrilateral_Order_3_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_quadrilateral_Order_3_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_tetrahedron_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_tetrahedron_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_tetrahedron_Order_3_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_hexahedron_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_hexahedron_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_1_Mesh_hexahedron_Order_3_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_line_Order_1_Dims_1.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_line_Order_1_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_line_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_line_Order_2_Dims_1.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_line_Order_2_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_line_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_line_Order_3_Dims_1.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_line_Order_3_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_line_Order_3_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_triangle_Order_1_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_triangle_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_triangle_Order_2_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_triangle_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_triangle_Order_3_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_triangle_Order_3_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_quadrilateral_Order_1_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_quadrilateral_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_quadrilateral_Order_2_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_quadrilateral_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_quadrilateral_Order_3_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_quadrilateral_Order_3_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_tetrahedron_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_tetrahedron_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_tetrahedron_Order_3_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_hexahedron_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_hexahedron_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_2_Mesh_hexahedron_Order_3_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_line_Order_1_Dims_1.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_line_Order_1_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_line_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_line_Order_2_Dims_1.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_line_Order_2_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_line_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_line_Order_3_Dims_1.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_line_Order_3_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_line_Order_3_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_triangle_Order_1_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_triangle_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_triangle_Order_2_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_triangle_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_triangle_Order_3_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_triangle_Order_3_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_quadrilateral_Order_1_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_quadrilateral_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_quadrilateral_Order_2_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_quadrilateral_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_quadrilateral_Order_3_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_quadrilateral_Order_3_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_tetrahedron_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_tetrahedron_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_tetrahedron_Order_3_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_hexahedron_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_hexahedron_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_3_Mesh_hexahedron_Order_3_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_line_Order_1_Dims_1.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_line_Order_1_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_line_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_line_Order_2_Dims_1.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_line_Order_2_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_line_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_line_Order_3_Dims_1.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_line_Order_3_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_line_Order_3_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_triangle_Order_1_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_triangle_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_triangle_Order_2_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_triangle_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_triangle_Order_3_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_triangle_Order_3_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_quadrilateral_Order_1_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_quadrilateral_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_quadrilateral_Order_2_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_quadrilateral_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_quadrilateral_Order_3_Dims_2.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_quadrilateral_Order_3_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_tetrahedron_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_tetrahedron_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_tetrahedron_Order_3_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_hexahedron_Order_1_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_hexahedron_Order_2_Dims_3.h"
#include "pbatautogen/LaplacianMatrix_4_Mesh_hexahedron_Order_3_Dims_3.h"

namespace pbat {
namespace py {
namespace fem {

void BindLaplacianMatrix(pybind11::module& m)
{
    BindLaplacianMatrix_1_Mesh_line_Order_1_Dims_1(m);
BindLaplacianMatrix_1_Mesh_line_Order_1_Dims_2(m);
BindLaplacianMatrix_1_Mesh_line_Order_1_Dims_3(m);
BindLaplacianMatrix_1_Mesh_line_Order_2_Dims_1(m);
BindLaplacianMatrix_1_Mesh_line_Order_2_Dims_2(m);
BindLaplacianMatrix_1_Mesh_line_Order_2_Dims_3(m);
BindLaplacianMatrix_1_Mesh_line_Order_3_Dims_1(m);
BindLaplacianMatrix_1_Mesh_line_Order_3_Dims_2(m);
BindLaplacianMatrix_1_Mesh_line_Order_3_Dims_3(m);
BindLaplacianMatrix_1_Mesh_triangle_Order_1_Dims_2(m);
BindLaplacianMatrix_1_Mesh_triangle_Order_1_Dims_3(m);
BindLaplacianMatrix_1_Mesh_triangle_Order_2_Dims_2(m);
BindLaplacianMatrix_1_Mesh_triangle_Order_2_Dims_3(m);
BindLaplacianMatrix_1_Mesh_triangle_Order_3_Dims_2(m);
BindLaplacianMatrix_1_Mesh_triangle_Order_3_Dims_3(m);
BindLaplacianMatrix_1_Mesh_quadrilateral_Order_1_Dims_2(m);
BindLaplacianMatrix_1_Mesh_quadrilateral_Order_1_Dims_3(m);
BindLaplacianMatrix_1_Mesh_quadrilateral_Order_2_Dims_2(m);
BindLaplacianMatrix_1_Mesh_quadrilateral_Order_2_Dims_3(m);
BindLaplacianMatrix_1_Mesh_quadrilateral_Order_3_Dims_2(m);
BindLaplacianMatrix_1_Mesh_quadrilateral_Order_3_Dims_3(m);
BindLaplacianMatrix_1_Mesh_tetrahedron_Order_1_Dims_3(m);
BindLaplacianMatrix_1_Mesh_tetrahedron_Order_2_Dims_3(m);
BindLaplacianMatrix_1_Mesh_tetrahedron_Order_3_Dims_3(m);
BindLaplacianMatrix_1_Mesh_hexahedron_Order_1_Dims_3(m);
BindLaplacianMatrix_1_Mesh_hexahedron_Order_2_Dims_3(m);
BindLaplacianMatrix_1_Mesh_hexahedron_Order_3_Dims_3(m);
BindLaplacianMatrix_2_Mesh_line_Order_1_Dims_1(m);
BindLaplacianMatrix_2_Mesh_line_Order_1_Dims_2(m);
BindLaplacianMatrix_2_Mesh_line_Order_1_Dims_3(m);
BindLaplacianMatrix_2_Mesh_line_Order_2_Dims_1(m);
BindLaplacianMatrix_2_Mesh_line_Order_2_Dims_2(m);
BindLaplacianMatrix_2_Mesh_line_Order_2_Dims_3(m);
BindLaplacianMatrix_2_Mesh_line_Order_3_Dims_1(m);
BindLaplacianMatrix_2_Mesh_line_Order_3_Dims_2(m);
BindLaplacianMatrix_2_Mesh_line_Order_3_Dims_3(m);
BindLaplacianMatrix_2_Mesh_triangle_Order_1_Dims_2(m);
BindLaplacianMatrix_2_Mesh_triangle_Order_1_Dims_3(m);
BindLaplacianMatrix_2_Mesh_triangle_Order_2_Dims_2(m);
BindLaplacianMatrix_2_Mesh_triangle_Order_2_Dims_3(m);
BindLaplacianMatrix_2_Mesh_triangle_Order_3_Dims_2(m);
BindLaplacianMatrix_2_Mesh_triangle_Order_3_Dims_3(m);
BindLaplacianMatrix_2_Mesh_quadrilateral_Order_1_Dims_2(m);
BindLaplacianMatrix_2_Mesh_quadrilateral_Order_1_Dims_3(m);
BindLaplacianMatrix_2_Mesh_quadrilateral_Order_2_Dims_2(m);
BindLaplacianMatrix_2_Mesh_quadrilateral_Order_2_Dims_3(m);
BindLaplacianMatrix_2_Mesh_quadrilateral_Order_3_Dims_2(m);
BindLaplacianMatrix_2_Mesh_quadrilateral_Order_3_Dims_3(m);
BindLaplacianMatrix_2_Mesh_tetrahedron_Order_1_Dims_3(m);
BindLaplacianMatrix_2_Mesh_tetrahedron_Order_2_Dims_3(m);
BindLaplacianMatrix_2_Mesh_tetrahedron_Order_3_Dims_3(m);
BindLaplacianMatrix_2_Mesh_hexahedron_Order_1_Dims_3(m);
BindLaplacianMatrix_2_Mesh_hexahedron_Order_2_Dims_3(m);
BindLaplacianMatrix_2_Mesh_hexahedron_Order_3_Dims_3(m);
BindLaplacianMatrix_3_Mesh_line_Order_1_Dims_1(m);
BindLaplacianMatrix_3_Mesh_line_Order_1_Dims_2(m);
BindLaplacianMatrix_3_Mesh_line_Order_1_Dims_3(m);
BindLaplacianMatrix_3_Mesh_line_Order_2_Dims_1(m);
BindLaplacianMatrix_3_Mesh_line_Order_2_Dims_2(m);
BindLaplacianMatrix_3_Mesh_line_Order_2_Dims_3(m);
BindLaplacianMatrix_3_Mesh_line_Order_3_Dims_1(m);
BindLaplacianMatrix_3_Mesh_line_Order_3_Dims_2(m);
BindLaplacianMatrix_3_Mesh_line_Order_3_Dims_3(m);
BindLaplacianMatrix_3_Mesh_triangle_Order_1_Dims_2(m);
BindLaplacianMatrix_3_Mesh_triangle_Order_1_Dims_3(m);
BindLaplacianMatrix_3_Mesh_triangle_Order_2_Dims_2(m);
BindLaplacianMatrix_3_Mesh_triangle_Order_2_Dims_3(m);
BindLaplacianMatrix_3_Mesh_triangle_Order_3_Dims_2(m);
BindLaplacianMatrix_3_Mesh_triangle_Order_3_Dims_3(m);
BindLaplacianMatrix_3_Mesh_quadrilateral_Order_1_Dims_2(m);
BindLaplacianMatrix_3_Mesh_quadrilateral_Order_1_Dims_3(m);
BindLaplacianMatrix_3_Mesh_quadrilateral_Order_2_Dims_2(m);
BindLaplacianMatrix_3_Mesh_quadrilateral_Order_2_Dims_3(m);
BindLaplacianMatrix_3_Mesh_quadrilateral_Order_3_Dims_2(m);
BindLaplacianMatrix_3_Mesh_quadrilateral_Order_3_Dims_3(m);
BindLaplacianMatrix_3_Mesh_tetrahedron_Order_1_Dims_3(m);
BindLaplacianMatrix_3_Mesh_tetrahedron_Order_2_Dims_3(m);
BindLaplacianMatrix_3_Mesh_tetrahedron_Order_3_Dims_3(m);
BindLaplacianMatrix_3_Mesh_hexahedron_Order_1_Dims_3(m);
BindLaplacianMatrix_3_Mesh_hexahedron_Order_2_Dims_3(m);
BindLaplacianMatrix_3_Mesh_hexahedron_Order_3_Dims_3(m);
BindLaplacianMatrix_4_Mesh_line_Order_1_Dims_1(m);
BindLaplacianMatrix_4_Mesh_line_Order_1_Dims_2(m);
BindLaplacianMatrix_4_Mesh_line_Order_1_Dims_3(m);
BindLaplacianMatrix_4_Mesh_line_Order_2_Dims_1(m);
BindLaplacianMatrix_4_Mesh_line_Order_2_Dims_2(m);
BindLaplacianMatrix_4_Mesh_line_Order_2_Dims_3(m);
BindLaplacianMatrix_4_Mesh_line_Order_3_Dims_1(m);
BindLaplacianMatrix_4_Mesh_line_Order_3_Dims_2(m);
BindLaplacianMatrix_4_Mesh_line_Order_3_Dims_3(m);
BindLaplacianMatrix_4_Mesh_triangle_Order_1_Dims_2(m);
BindLaplacianMatrix_4_Mesh_triangle_Order_1_Dims_3(m);
BindLaplacianMatrix_4_Mesh_triangle_Order_2_Dims_2(m);
BindLaplacianMatrix_4_Mesh_triangle_Order_2_Dims_3(m);
BindLaplacianMatrix_4_Mesh_triangle_Order_3_Dims_2(m);
BindLaplacianMatrix_4_Mesh_triangle_Order_3_Dims_3(m);
BindLaplacianMatrix_4_Mesh_quadrilateral_Order_1_Dims_2(m);
BindLaplacianMatrix_4_Mesh_quadrilateral_Order_1_Dims_3(m);
BindLaplacianMatrix_4_Mesh_quadrilateral_Order_2_Dims_2(m);
BindLaplacianMatrix_4_Mesh_quadrilateral_Order_2_Dims_3(m);
BindLaplacianMatrix_4_Mesh_quadrilateral_Order_3_Dims_2(m);
BindLaplacianMatrix_4_Mesh_quadrilateral_Order_3_Dims_3(m);
BindLaplacianMatrix_4_Mesh_tetrahedron_Order_1_Dims_3(m);
BindLaplacianMatrix_4_Mesh_tetrahedron_Order_2_Dims_3(m);
BindLaplacianMatrix_4_Mesh_tetrahedron_Order_3_Dims_3(m);
BindLaplacianMatrix_4_Mesh_hexahedron_Order_1_Dims_3(m);
BindLaplacianMatrix_4_Mesh_hexahedron_Order_2_Dims_3(m);
BindLaplacianMatrix_4_Mesh_hexahedron_Order_3_Dims_3(m);  
}

} // namespace fem
} // namespace py
} // namespace pbat
