site_name: "Physics Based Animation Toolkit"
site_url: "https://your-documentation-url.com"  # Replace with your actual documentation URL
site_description: "Comprehensive documentation for the Physics Based Animation Toolkit."
site_author: "Quoc-Minh Ton-That"

# Repository settings for edit links
repo_url: "https://github.com/Q-Minh/PhysicsBasedAnimationToolkit"
repo_name: "Q-Minh/PhysicsBasedAnimationToolkit"
edit_uri: "blob/main/docs"

# Theme configuration
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/brightness-4
        name: "Switch to light mode"
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - toc.follow
    - content.tabs.link
  favicon: "assets/imgs/favicon.ico"
  logo: "assets/imgs/pbat.svg"
  # Remove custom_dir if you don't have a custom theme directory
  # custom_dir: "theme"

# Navigation structure
nav:
  - Home: index.md
  - Overview: overview.md
  - Quick Start:
      - Introduction: quick_start/index.md
      - C++: quick_start/cpp.md
      - Python: quick_start/python.md
      - Tutorial: quick_start/tutorial.md
  - Dependencies:
      - Overview: dependencies/index.md
      - CUDA: dependencies/cuda.md
  - Configuration: configuration.md
  - Build & Install:
      - Overview: build_install/index.md
      - C++: build_install/cpp.md
      - Python: build_install/python.md
  - Install: install.md
  - Gallery: gallery.md
  - Contributing: contributing.md
  - The Finite Element Method:
      - Introduction: fem/index.md
      - Prerequisites: fem/prerequisites.md
      - Method: fem/method.md
      - Shape Functions: fem/shape_functions.md
      - Spatial Integration: fem/spatial_integration.md
      - Operators: fem/operators.md
      - Boundary Conditions: fem/boundary_conditions.md
      - Vector-valued Functions: fem/vector_valued_functions.md
      - Limitations: fem/limitations.md
      - Workshops: fem/workshops.md
  - Changelog: changelog.md

# Markdown extensions and plugins
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - mkdocs_graphviz
  - tables
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings
  - bibtex:
      bib_file: "docs/refs.bib"
  - include-markdown
  - git-revision-date-localized:
      locale: "en"
  - mkdocs-jupyter

# Paths to static files (CSS, JS, images)
extra_css:
  - "stylesheets/custom.css"

extra_javascript:
  - javascripts/config.js
  - javascripts/custom.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js

# Static files to include
extra:
  css:
    - "stylesheets/custom.css"
  js:
    - "javascripts/custom.js"

use_directory_urls: true
strict: true