pbat::math::Rational
std::int64_t pbat::math::Rational::a
Numerator.
Referenced by operator+, operator-, operator*, operator/, operator==, operator<, Rebase, simplify.
std::int64_t pbat::math::Rational::b
Denominator.
Referenced by operator+, operator-, operator*, operator/, operator==, operator<, Rebase, simplify.
pbat::math::Rational::Rational()
Construct a new Rational object.
Referenced by operator*, operator+, operator-, operator/.
pbat::math::Rational::Rational(Integer a, Integer b)
Construct a new Rational object.
a b
pbat::math::Rational::Rational(Integer value)
Construct a new Rational object.
value
Rational pbat::math::Rational::operator+(Rational const &) const
References a, b, Rational.
Rational pbat::math::Rational::operator-(Rational const &) const
Rational pbat::math::Rational::operator-() const
References a, b, Rational.
Rational pbat::math::Rational::operator*(Rational const &) const
References a, b, Rational.
Rational pbat::math::Rational::operator/(Rational const &) const
References a, b, Rational.
bool pbat::math::Rational::operator==(Rational const &) const
References a, b.
bool pbat::math::Rational::operator<(Rational const &) const
References a, b.
bool pbat::math::Rational::Rebase(std::int64_t denominator)
denominator true false
References a, b.
pbat::math::Rational::operator Scalar() const
Scalar
void pbat::math::Rational::simplify()
Attempts to reduce magnitude of a,b by eliminating common divisor.
References a, b.