pbat::sim::vbd::lod::Level
MatrixX pbat::sim::vbd::lod::Level::x
3x|#cage verts| deformed positions
Referenced by Level, pbat::sim::vbd::lod::Prolongation::Apply, pbat::sim::vbd::lod::Prolongation::DoApply, pbat::sim::vbd::lod::Restriction::Apply, pbat::sim::vbd::lod::Restriction::DoApply.
IndexVectorX pbat::sim::vbd::lod::Level::colors
Coarse vertex graph coloring.
Referenced by Level.
IndexVectorX pbat::sim::vbd::lod::Level::ptr
IndexVectorX pbat::sim::vbd::lod::Level::adj
Parallel vertex partitions.
Referenced by pbat::sim::vbd::lod::Restriction::DoApply.
VolumeMesh pbat::sim::vbd::lod::Level::mesh
Cage linear tetrahedral FEM mesh.
Referenced by Level, WithCageQuadrature, WithDirichletQuadrature, pbat::sim::vbd::lod::Prolongation::DoApply, pbat::sim::vbd::lod::Restriction::Apply, pbat::sim::vbd::lod::Restriction::DoApply.
CageQuadrature pbat::sim::vbd::lod::Level::Qcage
Cage volumetric quadrature.
Referenced by pbat::sim::vbd::lod::Hierarchy::Hierarchy, WithCageQuadrature, WithMomentumEnergy, WithElasticEnergy, pbat::sim::vbd::lod::Restriction::DoApply.
DirichletQuadrature pbat::sim::vbd::lod::Level::Qdirichlet
Cage Dirichlet quadrature.
Referenced by WithDirichletQuadrature, WithDirichletEnergy.
MomentumEnergy pbat::sim::vbd::lod::Level::Ekinetic
\frac{1}{2} \rho || x^c - \Tilde{x} ||_2^2
Referenced by WithMomentumEnergy, pbat::sim::vbd::lod::Restriction::DoApply.
ElasticEnergy pbat::sim::vbd::lod::Level::Epotential
\Psi(x^c)
Referenced by WithElasticEnergy, pbat::sim::vbd::lod::Restriction::DoApply.
DirichletEnergy pbat::sim::vbd::lod::Level::Edirichlet
\frac{1}{2} \mu_D || x^c - x_D ||_2^2
Referenced by WithDirichletEnergy.
pbat::sim::vbd::lod::Level::Level(VolumeMesh CM)
CM This level's finite element mesh
References colors, pbat::fem::Mesh< TElement, Dims >::E, mesh, pbat::fem::Mesh< TElement, Dims >::X, x.
Level & pbat::sim::vbd::lod::Level::WithCageQuadrature(Data const &problem, CageQuadratureParameters const &params)
Constructs this level's cage quadrature.
problem params
References mesh, pbat::sim::vbd::Data::mesh, Qcage.
Level & pbat::sim::vbd::lod::Level::WithDirichletQuadrature(Data const &problem)
Constructs this level's Dirichlet quadrature.
problem
References pbat::sim::vbd::Data::dbc, pbat::sim::vbd::Data::m, mesh, pbat::sim::vbd::Data::mesh, Qdirichlet.
Referenced by pbat::sim::vbd::lod::Hierarchy::Hierarchy.
Level & pbat::sim::vbd::lod::Level::WithMomentumEnergy(Data const &problem)
Constructs this level's momentum energy.
problem
References Ekinetic, Qcage.
Referenced by pbat::sim::vbd::lod::Hierarchy::Hierarchy.
Level & pbat::sim::vbd::lod::Level::WithElasticEnergy(Data const &problem)
Constructs this level's elastic energy.
problem
References Epotential, Qcage.
Referenced by pbat::sim::vbd::lod::Hierarchy::Hierarchy.
Level & pbat::sim::vbd::lod::Level::WithDirichletEnergy(Data const &problem)
problem
References Edirichlet, Qdirichlet.
Referenced by pbat::sim::vbd::lod::Hierarchy::Hierarchy.