site_name: "Physics Based Animation Toolkit"
site_url: "https://your-documentation-url.com"  # Replace with your documentation URL
site_description: "Comprehensive documentation for the Physics Based Animation Toolkit."
site_author: "Quoc-Minh Ton-That"

# Repository settings for edit links
repo_url: "https://github.com/Q-Minh/PhysicsBasedAnimationToolkit"
repo_name: "Q-Minh/PhysicsBasedAnimationToolkit"
repo_type: git
edit_uri: "blob/main/docs"

# Theme configuration
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/brightness-4
        name: "Switch to light mode"
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - toc.follow
    - content.tabs.link
  favicon: "assets/imgs/favicon.ico"
  logo: "assets/imgs/pbat.svg"
  custom_dir: "theme"  # If you have custom theme overrides

# Navigation structure
nav:
  - Home: index.md
  - Overview: overview.md
  - Quick Start:
      - Introduction: quick_start/index.md
      - C++: quick_start/cpp.md
      - Python: quick_start/python.md
      - Tutorial: quick_start/tutorial.md
  - Dependencies:
      - Overview: dependencies/index.md
      - CUDA: dependencies/cuda.md
  - Configuration: configuration.md
  - Build & Install:
      - Overview: build_install/index.md
      - C++: build_install/cpp.md
      - Python: build_install/python.md
  - Install: install.md
  - Gallery: gallery.md
  - Contributing: contributing.md
  - The Finite Element Method:
      - Introduction: fem/index.md
      - Prerequisites: fem/prerequisites.md
      - Method: fem/method.md
      - Shape Functions: fem/shape_functions.md
      - Spatial Integration: fem/spatial_integration.md
      - Operators: fem/operators.md
      - Boundary Conditions: fem/boundary_conditions.md
      - Vector-valued Functions: fem/vector_valued_functions.md
      - Limitations: fem/limitations.md
      - Workshops: fem/workshops.md
  - Changelog: changelog.md   # Added Changelog to Navigation

# Markdown extensions and plugins
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - mathjax
  - graphviz
  - bibtex
  - mkdocstrings
  - include-markdown
  - git-revision-date-localized:
      format: '%b %d, %Y'
  - material:
      features:
        - navigation.tabs
        - content.code.annotate
        - content.code.copy
        - content.tabs.link
      palette:
        primary: deep-purple
        accent: deep-purple
      font:
        text: Roboto
        code: Roboto Mono

  # mkdocs-material specific plugin configurations
  - bibtex:
      bibfiles:
        - refs.bib
      include_refs: true

  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_inherited_members: true
            show_private_members: true
            show_special_members: true

  # Include plugin for including markdown files within others
  - include-markdown

# Paths to static files (CSS, JS, images)
extra_css:
  - "stylesheets/custom.css"

extra_javascript:
  - "javascripts/custom.js"

# Static files to include
extra:
  - "assets/imgs/"

# Extra configurations
use_directory_urls: true
strict: true

# Define the build directory
# By default, mkdocs uses 'site' as the output directory
# You can change it if necessary
# build_dir: "build"

# GitHub Pages branch (if deploying to GitHub Pages)
# For example, 'gh-pages'
# deploy:
#   provider: pages
#   branch: gh-pages
#   token: $GITHUB_TOKEN  # Set in environment variables