name: Docs

on:
  push:
    branches:
      - main
      - docs

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 1

      - name: Setup CMake
        uses: lukka/get-cmake@v12
        with:
          cmakeVersion: "3.26.0"

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/vcpkg
          vcpkgGitCommitId: 055721089e8037d4d617250814d11f881e557549

      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: "3.12"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz ccache

          # Install MkDocs and related dependencies
          pip install mkdocs mkdocs-material mkdocstrings mkdocs-bibtex

          echo 'CACHE_PATH=/home/runner/.cache/ccache' >> "$GITHUB_ENV"

      - name: Upgrade pip and Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Cache Ccache
        id: cache-build
        uses: actions/cache@v4.0.2
        with:
          path: /home/runner/.cache/ccache
          key: ccache-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt', 'docs/requirements.txt') }}
          restore-keys: |
            ccache-${{ runner.os }}-

      - name: Configure Ccache
        run: |
          ccache --max-size=1.0G
          ccache --zero-stats

      - name: Build Python Package
        run: |
          pip install setuptools mkdocstrings
          pip install . --config-settings=cmake.args="--preset=pip" --config-settings=build.tool-args="-j4" -v
          ccache --show-stats

      - name: Build Documentation with MkDocs
        run: |
          mkdocs build --clean

      - name: Touch .nojekyll
        run: |
          cd site
          touch .nojekyll
          cd ..

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: site
          clean: true
