name: Docs

on:
  push:
    branches:
      - main
      - docs

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: "3.12"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz ccache

      - name: Upgrade pip and Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build Documentation with MkDocs
        run: |
          mkdocs build --clean

      - name: Touch .nojekyll
        run: |
          cd site
          touch .nojekyll
          cd ..

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: site
          clean: true
